### ISSUE TITLE
Document App Promotion

### ISSUE THREAD

**Issue by deobald** [pariyatti/mobile-app#113]
Stub document is here: https://github.com/pariyatti/mobile-app/blob/master/doc/RELEASING.md 

Images can go in https://github.com/pariyatti/mobile-app/blob/master/doc/img/

**Comment by balwa** [comment]
I have updated the android documentation in the branch, though it turns out somewhere in the process of trying to troubleshoot the publishing the iOS app failure, I forgot to take AppConnect screenshots. So, that bit remains a TODO until the new release for iOS is done and shall update the documentation for it.
